#:kivy 2.3.1
#:import EkranSabit sabitler.EkranSabit

<PencereYonetici>:
    AnaPencere:
    
<DenemePencere>:
    name:"denemePencere"
    Label:
        text:"Burası Deneme Penceresi"


<AnaPencere>:
    canvas.before:
        Color:
            rgba:1,1,1,1
        Rectangle:
            size:self.size
            pos:self.pos
    id:anaPencere
    name:"anaPencere"
    BoxLayout:
        orientation:'horizontal'
        size_hint:1,1

        BoxLayout:
            id:solPanel
            orientation:'vertical'
            size_hint_x:EkranSabit.SOL_PANEL_GENISLIK_ORAN
            canvas.before:
                Color:
                    rgba:.5,.1,.2,1
                Rectangle:
                    size:self.size
                    pos:self.pos

            Label:
                text:"Burası Sol Panel"
            
        BoxLayout:
            orientation:'vertical'
            id:yarismaPanel
            size_hint_x:EkranSabit.SAHA_GENISLIK_ORAN

            BoxLayout:
                orientation:'horizontal'
                size_hint_y:EkranSabit.SAHA_UST_YUKSEKLIK_ORAN
                canvas.before:
                    Color:
                        rgba:.2,.5,.2,1
                    Rectangle:
                        size:self.size
                        pos:self.pos
                Label:
                    text:"Üst"
                
                
                    
            Saha:
                canvas.before:
                    Color:
                        rgba:.2,.2,.2,.2
                    Rectangle:
                        size:self.size
                        pos:self.pos
                id:saha
                size_hint_y:EkranSabit.SAHA_YUKSEKLIK_ORAN


            BoxLayout:
                orientation:'horizontal'
                size_hint_y:EkranSabit.SAHA_ALT_YUKSEKLIK_ORAN
                canvas.before:
                    Color:
                        rgba:.1,.5,.7,1
                    Rectangle:
                        size:self.size
                        pos:self.pos
                Label:
                    text:"Alt"
                
                Button:
                    text:"Başlat"
                    on_press:root.yarisBaslatClick()
                    


        BoxLayout:
            orientation:'vertical'
            id:sagPanel
            size_hint_x:EkranSabit.SAG_PANEL_GENISLIK_ORAN
            canvas.before:
                Color:
                    rgba:.2,.1,.5,1
                Rectangle:
                    size:self.size
                    pos:self.pos
            Label:
                text:"Burası Sağ Panel"